# Generated by Django 4.2.13 on 2024-08-03 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_rename_category_name_taskcategory_name_and_more'),
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskmodel',
            name='categories',
            field=models.ManyToManyField(related_name='tasks', to='category.taskcategory'),
        ),
        migrations.AlterField(
            model_name='taskmodel',
            name='taskTitle',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='taskmodel',
            name='task_assign_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
